### PR TITLE
Update IOS and Android projects

### PR DESCRIPTION
**Pull request by Vanethos**
Updated android and ios projects via `flutter create .`
Added necessary platform channels code to Main Activity

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
@RedBrogdon

**Comment by Vanethos** [comment]
Thanks for the tag @eseidelGoogle ! I'll wait for @RedBrogdon for a review :D 

Again, I made this PR since I couldn't launch the app as it was, so, I just updated both android and ios projects so that it could be cloned and run normally

**Comment by yjbanov** [comment]
For some reason I wasn't able to run the app with this change. The tools complain that I need to upgrade the project to "AndroidX", but gradle fails to do that :(

**Comment by yjbanov** [comment]
Fixes https://github.com/flutter/flutter/issues/27248
Fixes https://github.com/flutter/flutter/issues/28890

**Comment by bruno-garcia** [comment]
@Vanethos we merged #7 which added travis builds but also fixed the Crashy.
I believe this PR is not needed anymore, would you agree?

**Comment by Vanethos** [comment]
Sorry for the late reply!

Yeah, totally agree, going to close it :+1:

**Pull request closed without merging**
