### PR TITLE
Upgrade xcode 11.4

### PR DESCRIPTION
**Pull request by bruno-garcia**
Following the suggestions xcode gave after upgrade

/cc @yjbanov

### CODE REVIEW

**Comment by Hixie** [comment]
cc @xster @jonahwilliams who's the best person to review this?

**Comment by jmagman** [comment]
You may also hit https://github.com/flutter/flutter/issues/50568, can you also follow the migration instructions at https://flutter.dev/docs/development/ios-project-migration to remove the Flutter.framework and App.framework embedding?

**Comment by jmagman** [comment]
These changes look good, feel free to do that [migration](https://flutter.dev/docs/development/ios-project-migration) in another PR and add me as a reviewer.  Up to you!

**Comment by bruno-garcia** [comment]
@jmagman thanks a lot for reviewing my changes.
I'll open a follow up PR with the migration.

Would you [please review my open PRs on sentry](https://github.com/flutter/sentry/pulls/bruno-garcia) too? Thank you.

**Comment by yjbanov** [comment]
Is this good to submit?

**Comment by jmagman** [comment]
The code LGTM but I have no idea how to test crashy.  It still doesn't seem enabled on Travis? https://travis-ci.org/github/flutter/crashy.

**Comment by jmagman** [comment]
I just checked out the branch, these changes look good.  Merging.

**Pull request merged**
