### PR TITLE
feat: add travis ci

### PR DESCRIPTION
**Pull request by bruno-garcia**
Supersedes #6 

Would need someone with permison on travis to add the repo.
I've already added the badge pointing to this repo's master.

`classpath 'com.android.tools.build:gradle:3.5.0'` as 3.5.2 is not yet supported

### CODE REVIEW

**Comment by bruno-garcia** [comment]
@yjbanov Let me know if you need anything to get this change in.

**Comment by yjbanov** [comment]
I don't see Travis in the list of checks. Does it kick in after the PR is merged?

**Comment by bruno-garcia** [comment]
@yjbanov You'd need to go on travis-ci.org and add this repo there first.
I did that for my branch to be able to test it out.

Once it's added I can close/reopen the PR to trigger the build.

**Comment by yjbanov** [comment]
Thanks for the instructions! Let me give it a shot.

**Comment by dnfield** [comment]
@bruno-garcia WDYT of moving this over to github.com/flutter/samples? Travis is already set up there, and would likely mean this gets a bit more attention than it currently has.

/cc @RedBrogdon

**Comment by bruno-garcia** [comment]
@dnfield Whatever is best for you all.

I'll be contributing more PRs for `crashy` either way, and to `github.com/flutter/sentry`, just wanted to CI here first before I start messing around. :)

**Comment by yjbanov** [comment]
@dnfield @RedBrogdon Have you decided what you want to do here?

**Comment by bruno-garcia** [comment]
FYI this change bundled #6 and CI to verify it now builds (so that @yjbanov wouldn't need to verify manually).

#6 anyway makes sure it builds with latest tools. Previous was 3 years old sdks and sentry package.

Perhaps we can merge this and have that decision of moving the code to the other repo done separately?

**Comment by dnfield** [comment]
I see no harm in merging this with or without travis enablement.

I do suspect that this repository should not remain as is though - it's not being actively maintained here.  @bruno-garcia - do you think Sentry would be interested in taking over this repository?  Perhaps archiving it here with a pointer to something at Sentry?

**Comment by bruno-garcia** [comment]
Sentry just added docs pointing to `flutter.dev` and it's great to see the work done here.
That said, we love the support Flutter has for Sentry and we'd like to contribute back. 

Regarding this specific repo, if you prefer, we'd be happy to take it and maintain in the `getsentry` GitHub org. Contributing here also works for us.

**Comment by yjbanov** [comment]
@bruno-garcia What would you say to moving the development of https://github.com/flutter/sentry to getsentry as well? I think it would make sense to have this package next to other frameworks that Sentry supports. That's where all the Sentry domain knowledge lives.

**Comment by bruno-garcia** [comment]
Thanks @yjbanov for offering. We'd be glad to bring this in and maintain it as a first-tier Sentry SDK.
I notice you have PATENTS in the repository. How would this affect the transfer?

Would it be possible to re-license the repo in this case?
We're aiming at having all our SDKs as MIT and we generally don't have license disclaimers as a header in source files.
If that's OK, I could open a PR to make these changes and once you've approved/merged in, we could make the repo transfer. How does that sound?
There's also the ownership of the package on `pub.dev`. Would you also be willing to transfer ownership of that?

**Comment by dnfield** [comment]
@Hixie

**Comment by Hixie** [comment]
The PATENT file should be no issue. The bigger problem is I just noticed that Google's clabot didn't trigger on this PR. Investigating...

**Comment by Hixie** [comment]
Ah, never mind, I was wrong, the bot is happy, just quiet. :-) 

In any case, if you want to fork the repo you are welcome to do that, it's just a regular open source repo. You're also welcome to contribute and own the code here. Generally relicensing is not likely to be viable, it would be a large amount of work to track down every last commit over the entire history of any code involved, it would have to be reviewed by lawyers, etc, etc, etc.

**Comment by bruno-garcia** [comment]
> You're also welcome to contribute and own the code here.

This sounds good if that works for you too.

If you enable the issue tracker on the repos (here and [flutter/sentry](https://github.com/flutter/sentry)) we'll be happy to maintain that too. Is that an options?

**Comment by Hixie** [comment]
Should be possible. Would you like to merge the two repos into one (e.g. putting crashy as an example directory in sentry)?

**Comment by bruno-garcia** [comment]
@Hixie That's how we maintain the other SDKs in Sentry. It's handy to test SDK features in the emulators.
I can raise a PR for that.

**Comment by bruno-garcia** [comment]
Can we merge this PR first?

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
@bruno-garcia BTW for the steps to get commit access please see our contributor guide. Basically so long as y'all apply the guidelines in our Tree Hygiene doc I think there shouldn't be any problems.

**Comment by yjbanov** [comment]
Just wanted to say: :tada: !!!

**Pull request merged**
